variable "aws_region" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
variable "public_cidr" {}
variable "availability_zone" {}
variable "subnet_name" {}
variable "igw_name" {}
variable "secgrp_name" {}
variable "image_name" {}
variable "instance_type" {}
variable "key_name" {}
variable "instance_name" {}
